---
author: "Noam Ross"
date: "March 10, 2015"
output: 
  html_document:
    fig_caption: yes
---

```{r get_archie_data, echo=FALSE, results='hide', warning=FALSE, error=FALSE, message=FALSE}
library(rchie)
library(driver) #note this is my branch of this package, which includes the gdoc_to_md function.
library(rmarkdown)
token = readRDS('token_file')
file_meta = file_metadata(token=token, file_id = '1CZ_lLPU-d4o9P4KgFbve9cYlNQSiL3QV8gFaiy0ssWA')
tmp = tempfile()
tmp2 = tempfile()
download_file(token = token, metadata = file_meta, download_type = 'text/html', destination=tmp, overwrite=TRUE)
gdoc_to_md(input_html=tmp, output_file=tmp2, options="--no-wrap")
aml = from_archie(tmp2)
```

### `r aml$header1`

`r aml$intro`

`r aml$about`

### `r aml$header2`

`r aml$charttext`

```{r plot, echo=TRUE, results='markup', fig.cap=aml$caption}
library(gspreadr)
library(magrittr)
library(ggplot2)
authorize()
gsheet = register_ss(key = "1Fn9UcY_hSAV2odttdIHB4xh9D_nmgI5hyCbtWrAJqkw", visibility="public", verbose=FALSE)
gdata = get_via_cf(gsheet) %>% reshape_cf
ggplot(gdata, aes(x=Category, y=Value)) + geom_bar(stat="identity") +
	scale_x_discrete(labels = aml$catnames, name = aml$xaxis) + 
	ylab(aml$yaxis)
```

`r aml$charttext2`

### `r aml$header3`

`r aml$thinking`

### `r aml$header4`

`r aml$rchie`

