# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
language: r
r:
  - oldrel
  - release
  - devel
addons:
  apt:
    packages:
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"
